# Generated by Django 3.1.1 on 2020-10-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201005_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Watch',
        ),
    ]
